#+title: No Weird Trick

* Posts

- [[file:quick-sort.org][Quick Sort]]

* About
#+begin_quote
Any sufficiently advanced technology is indistinguishable from magic.
#+end_quote
- Arthur C. Clarke, /Profiles of the Future/, 1962

When I first heard Arhur C. Clarke's [[https://en.wikipedia.org/wiki/Clarke%27s_three_laws][third law]], I thought science-fiction.
Clarke was a science-fiction author after all.
I imagined humanity interacting with aliens and finding them incomprehensible.
But the quote doesn't say "alien technology" or "future technology" - just "sufficiently advanced technology."
"Sufficiently advanced" is personal.

For a baby, the idea that an object doesn't disappear when it is obscured by another object might be sufficiently advanced.
For me, electricity is sufficiently advanced (not to brag about my object-permanence skills).
I live with electricity, I am reasonably comfortable with it, but I don't understand it - not really - it may as well be magic to me.

That being said I think that understanding - taking things from the realm of the sufficiently advanced to the insufficiently advanced - eliminating magic - is really fun.
I want to write things that help people understand.
The reader of those things, sure, but me as the writer even more.
I want to show that there really is no magic, no tricks.
As a play on ads that promise "one weird trick to do X," I want to show that, for most things, there are no weird tricks.

Each post is designed to illustrate a certain concept.
The posts are literate programs written in org-mode.
That means that each post is [[https://github.com/nuts4nuts4nuts/noweirdtrick/tree/main/src][source code]] which produces:
1. The post itself
2. The executable program that is built up in the post
